/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mmissen (https://sketchfab.com/mmissen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/space-ship-concept-toon-d010516c98404e009283b5f118e7455c
title: Space Ship Concept Toon
*/

import React, { useRef } from 'react'
import { useGLTFLoader } from '@react-three/drei/loaders/useGLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTFLoader('/model.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={[1.3,1.3,1.3]}>
      <group rotation={[-Math.PI / 2, 0, 3]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -0.06]}>
            <mesh material={materials.material} geometry={nodes.mesh_0.geometry} />
          </group>
          <group position={[0, 0, -0.81]}>
            <mesh material={materials.Material} geometry={nodes.mesh_1.geometry} />
          </group>
          <group position={[0, 0.98, 0.15]} rotation={[1.57, 0, 0]} scale={[0.49, 0.69, 0.49]}>
            <mesh material={materials['Material.001']} geometry={nodes.mesh_2.geometry} />
          </group>
          <group position={[1.41, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.002']} geometry={nodes.mesh_3.geometry} />
          </group>
          <group position={[1.41, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.004']} geometry={nodes.mesh_4.geometry} />
          </group>
          <group position={[0.01, 0.68, -0.45]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.41, 0.37]}>
            <mesh material={materials['Material.005']} geometry={nodes.mesh_5.geometry} />
          </group>
          <group position={[1.41, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.002']} geometry={nodes.mesh_6.geometry} />
          </group>
          <group position={[1.41, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials.Material} geometry={nodes.mesh_7.geometry} />
          </group>
          <group position={[1.41, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.003']} geometry={nodes.mesh_8.geometry} />
          </group>
          <group position={[-1.52, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.008']} geometry={nodes.mesh_9.geometry} />
          </group>
          <group position={[-1.52, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.007']} geometry={nodes.mesh_10.geometry} />
          </group>
          <group position={[-1.52, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.007']} geometry={nodes.mesh_11.geometry} />
          </group>
          <group position={[-1.52, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.006']} geometry={nodes.mesh_12.geometry} />
          </group>
          <group position={[-1.52, 0.55, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.54, 0.49]}>
            <mesh material={materials['Material.005']} geometry={nodes.mesh_13.geometry} />
          </group>
        </group>
      </group>
    </group>
  )
}
