/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kuat-Entralla 3D Engineering (https://sketchfab.com/KuatEntralla3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/acclamator-class-assault-ship-e6a2171be5c34bb68a05aba657fd8fa8
title: Acclamator-Class Assault Ship
*/

import React, { useRef } from 'react'
import { useGLTFLoader } from '@react-three/drei/loaders/useGLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTFLoader('/model3.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={[0.5, 0.5, 0.5]}>
      <group rotation={[-Math.PI / 2, 0, 3]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.84, 0.49, -17.5]} rotation={[-1.58, 0, 0]} scale={[0.2, 0.78, 0.2]}>
            <mesh material={materials['Material.018']} geometry={nodes.mesh_0.geometry} />
            <mesh material={materials['Material.017']} geometry={nodes.mesh_1.geometry} />
            <mesh material={materials['Material.016']} geometry={nodes.mesh_2.geometry} />
            <mesh material={materials['Material.002']} geometry={nodes.mesh_3.geometry} />
            <mesh material={materials['Material.001']} geometry={nodes.mesh_4.geometry} />
            <mesh material={materials['Material.003']} geometry={nodes.mesh_5.geometry} />
            <mesh material={materials['Material.012']} geometry={nodes.mesh_6.geometry} />
            <mesh material={materials['Material.011']} geometry={nodes.mesh_7.geometry} />
            <mesh material={materials['Material.010']} geometry={nodes.mesh_8.geometry} />
            <mesh material={materials['Material.015']} geometry={nodes.mesh_9.geometry} />
            <mesh material={materials['Material.014']} geometry={nodes.mesh_10.geometry} />
            <mesh material={materials['Material.013']} geometry={nodes.mesh_11.geometry} />
          </group>
          <group rotation={[-1.57, 0, 0]}>
            <mesh material={materials.Mat_1} geometry={nodes.mesh_12.geometry} />
            <mesh material={materials['Material.019']} geometry={nodes.mesh_13.geometry} />
            <mesh material={materials.Mat_2} geometry={nodes.mesh_14.geometry} />
            <mesh material={materials.Mat_0} geometry={nodes.mesh_15.geometry} />
          </group>
        </group>
      </group>
    </group>
  )
}
